package com.bankwel.phjf_website.common.model.website;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _PhjfMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _PhjfMappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("phjf_app_info", "app_id", AppInfo.class);
		arp.addMapping("phjf_bank_atm", "bank_atm_id", BankAtm.class);
		arp.addMapping("phjf_bank_info", "bank_id", BankInfo.class);
		arp.addMapping("phjf_bank_type", "bt_id", BankType.class);
		arp.addMapping("phjf_managepoint_info", "mp_id", ManagepointInfo.class);
		arp.addMapping("phjf_news_article", "na_id", NewsArticle.class);
		arp.addMapping("phjf_web_about_us", "au_id", WebAboutUs.class);
		arp.addMapping("phjf_web_app_download_info", "adi_id", WebAppDownloadInfo.class);
		arp.addMapping("phjf_web_banner", "banner_id", WebBanner.class);
		arp.addMapping("phjf_web_links", "links_id", WebLinks.class);
		arp.addMapping("phjf_web_nav", "nav_id", WebNav.class);
		arp.addMapping("phjf_web_news_info", "ni_id", WebNewsInfo.class);
		arp.addMapping("phjf_web_news_plate", "np_id", WebNewsPlate.class);
		arp.addMapping("phjf_web_partner", "partner_id", WebPartner.class);
	}
}

