package com.bankwel.phjf_website.common.model.website;

import com.bankwel.framework.core.F;
import com.bankwel.phjf_website.common.model.website.base.BaseManagepointInfo;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManagepointInfo extends BaseManagepointInfo<ManagepointInfo> {
	public static final ManagepointInfo dao = new ManagepointInfo().dao();

	/**
	 * 获取银行机构列表
	 * @return
	 */
	public List<ManagepointInfo> queryManagepointInfoList(String geohash, String lat, String lng){
		String sql = "select * " +
				"       from phjf_managepoint_info managepoint" +
				"      where geohash like concat(?,'%') " +
				"        and language = 'ZH_SIMP' " +
				"        and status = '1' " +
				"        and is_show = 'Y' " ;
		List params = new ArrayList();
		params.add(geohash);
		sql += "  and lat is not null and lng is not null  order by fun_dis(?,?,managepoint.lat,managepoint.lng)     limit 200 ";
		params.add(lat);
		params.add(lng);
		return dao.use("DBPublic").find(sql, params.toArray());
	}

	public  List<ManagepointInfo> queryAllManagepointInfo(){
		String sql = "select * " +
				"       from phjf_managepoint_info managepoint" ;

		return dao.use("DBPublic").find(sql);
	}
}
