package com.bankwel.phjf_website.common.model.website;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.util.DataLoader;
import com.bankwel.framework.support.codis.RedisClient;
import com.bankwel.phjf_website.common.model.website.base.BaseNewsArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsArticle extends BaseNewsArticle<NewsArticle> {
	public static final NewsArticle dao = new NewsArticle().dao();
	public NewsArticle findByCode(final String article_code,final String language){
		String sql = " SELECT * FROM phjf_news_article " +
				"       where article_code = ? " +
				"         and language = ? " +
//				"         and status = '2' " +
				"         and is_show = 'Y' limit 1";
		return NewsArticle.dao.use("DBPublic").findFirst(sql,article_code,language);
	}
}
