package com.bankwel.phjf_website.common.model.website;

import com.bankwel.phjf_website.common.model.website.base.BaseWebAppDownloadInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebAppDownloadInfo extends BaseWebAppDownloadInfo<WebAppDownloadInfo> {
	public static final WebAppDownloadInfo dao = new WebAppDownloadInfo().dao();
}
