package com.bankwel.phjf_website.common.model.website;

import com.bankwel.phjf_website.common.model.website.base.BaseWebAboutUs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebAboutUs extends BaseWebAboutUs<WebAboutUs> {
	public static final WebAboutUs dao = new WebAboutUs().dao();
}
