package com.bankwel.phjf_website.common.model.website;

import com.bankwel.phjf_website.common.model.website.base.BaseWebBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebBanner extends BaseWebBanner<WebBanner> {
	public static final WebBanner dao = new WebBanner().dao();
}
