package com.bankwel.phjf_website.common.model.website;

import com.bankwel.phjf_website.common.model.website.base.BaseWebLinks;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebLinks extends BaseWebLinks<WebLinks> {
	public static final WebLinks dao = new WebLinks().dao();
	/**
	 * 获取导航列表
	 * @return
	 */
	public List<WebLinks> queryLinksList(String language){
		String sql = "select * " +
				"       from phjf_web_links " +
				"      where language = ? " +
				"        and is_show = 'Y'" +
				"        and status = '1' order by orders ";
		return WebLinks.dao.use("DBPublic").find(sql,language);
	}
}
