package com.bankwel.phjf_website.common.model.website;

import com.bankwel.phjf_website.common.model.website.base.BaseWebNewsPlate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebNewsPlate extends BaseWebNewsPlate<WebNewsPlate> {
	public static final WebNewsPlate dao = new WebNewsPlate().dao();
}
