package com.bankwel.phjf_website.common.model.website;

import com.bankwel.phjf_website.common.model.website.base.BaseWebPartner;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebPartner extends BaseWebPartner<WebPartner> {
	public static final WebPartner dao = new WebPartner().dao();
	/**
	 * 获取导航列表
	 * @return
	 */
	public List<WebPartner> queryPartnerList(String language){
		String sql = "select * " +
				"       from phjf_web_partner " +
				"      where language = ? " +
				"        and is_show = 'Y'" +
				"        and status = '1' order by orders ";
		return WebPartner.dao.use("DBPublic").find(sql,language);
	}
}
