package com.bankwel.phjf_admin.catchsystem;

import com.jfinal.kit.PropKit;

/**
 * Generated by su_ln on 2016/4/13.
 */
public class CatchKeyConst {

    /*-----------------------------------------------------------------系统分界符---Sys--------------------------------------------------------------------------------*/
    public static final String CK_Sys = PropKit.use("config.properties").get("phjf.catch.sys.patch");
    public static final String CK_Sys_Model_SysDatalibrary = CK_Sys +".model.SysDatalibrary";

    /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

    /*-----------------------------------------------------------------系统分界符---其他部分--------------------------------------------------------------------------------*/

}
