package com.bankwel.phjf_website.catchsystem;

import com.jfinal.kit.PropKit;

/**
 * Generated by su_ln on 2016/4/13.
 */
public class CatchKeyConst {

    /*-----------------------------------------------------------------系统分界符---Stock--------------------------------------------------------------------------------*/
    public static final String CK_Phjf = PropKit.use("config.properties").get("phjf.codis.patch");
    public static final String CK_Phjf_Model_CmsBanner = CK_Phjf +".model.CmsBanner";
    public static final String CK_Phjf_Model_CmsCompanyCulture = CK_Phjf +".model.CmsCompanyCulture";
    public static final String CK_Phjf_Model_CmsContactInfo = CK_Phjf +".model.CmsContactInfo";
    public static final String CK_Phjf_Model_CmsContent = CK_Phjf +".model.CmsContent";
    public static final String CK_Phjf_CmsManager = CK_Phjf +".model.CmsManager";
    public static final String CK_Phjf_Model_CmsNav = CK_Phjf +".model.CmsNav";
    public static final String CK_Phjf_Model_CmsProgram = CK_Phjf +".model.CmsProgram";
    public static final String CK_Phjf_Model_CmsVocationalWork = CK_Phjf +".model.CmsVocationalWork";

    /*----------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

    /*-----------------------------------------------------------------系统分界符---其他部分--------------------------------------------------------------------------------*/

}
