package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setUser_id(java.lang.Integer user_id) {
		set("user_id", user_id);
	}

	public java.lang.Integer getUser_id() {
		return getInt("user_id");
	}

	public void setUser_name(java.lang.String user_name) {
		set("user_name", user_name);
	}

	public java.lang.String getUser_name() {
		return getStr("user_name");
	}

	public void setHead_img(java.lang.String head_img) {
		set("head_img", head_img);
	}

	public java.lang.String getHead_img() {
		return getStr("head_img");
	}

	public void setMobilephone(java.lang.String mobilephone) {
		set("mobilephone", mobilephone);
	}

	public java.lang.String getMobilephone() {
		return getStr("mobilephone");
	}

	public void setTrue_name(java.lang.String true_name) {
		set("true_name", true_name);
	}

	public java.lang.String getTrue_name() {
		return getStr("true_name");
	}

	public void setId_type(java.lang.String id_type) {
		set("id_type", id_type);
	}

	public java.lang.String getId_type() {
		return getStr("id_type");
	}

	public void setId_num(java.lang.String id_num) {
		set("id_num", id_num);
	}

	public java.lang.String getId_num() {
		return getStr("id_num");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}

	public java.lang.String getGender() {
		return getStr("gender");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setReg_time(java.util.Date reg_time) {
		set("reg_time", reg_time);
	}

	public java.util.Date getReg_time() {
		return get("reg_time");
	}

	public void setFrozen_time(java.util.Date frozen_time) {
		set("frozen_time", frozen_time);
	}

	public java.util.Date getFrozen_time() {
		return get("frozen_time");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
