package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserLoanBankProcess<M extends BaseUserLoanBankProcess<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setBlua_id(java.lang.Integer blua_id) {
		set("blua_id", blua_id);
	}

	public java.lang.Integer getBlua_id() {
		return getInt("blua_id");
	}

	public void setUlp_id(java.lang.Integer ulp_id) {
		set("ulp_id", ulp_id);
	}

	public java.lang.Integer getUlp_id() {
		return getInt("ulp_id");
	}

	public void setUser_id(java.lang.Integer user_id) {
		set("user_id", user_id);
	}

	public java.lang.Integer getUser_id() {
		return getInt("user_id");
	}

	public void setBt_code(java.lang.String bt_code) {
		set("bt_code", bt_code);
	}

	public java.lang.String getBt_code() {
		return getStr("bt_code");
	}

	public void setBank_code(java.lang.String bank_code) {
		set("bank_code", bank_code);
	}

	public java.lang.String getBank_code() {
		return getStr("bank_code");
	}

	public void setTrue_name(java.lang.String true_name) {
		set("true_name", true_name);
	}

	public java.lang.String getTrue_name() {
		return getStr("true_name");
	}

	public void setId_type(java.lang.String id_type) {
		set("id_type", id_type);
	}

	public java.lang.String getId_type() {
		return getStr("id_type");
	}

	public void setId_num(java.lang.String id_num) {
		set("id_num", id_num);
	}

	public java.lang.String getId_num() {
		return getStr("id_num");
	}

	public void setMobilephone(java.lang.String mobilephone) {
		set("mobilephone", mobilephone);
	}

	public java.lang.String getMobilephone() {
		return getStr("mobilephone");
	}

	public void setLoan_use_type(java.lang.String loan_use_type) {
		set("loan_use_type", loan_use_type);
	}

	public java.lang.String getLoan_use_type() {
		return getStr("loan_use_type");
	}

	public void setLoan_amount(java.lang.String loan_amount) {
		set("loan_amount", loan_amount);
	}

	public java.lang.String getLoan_amount() {
		return getStr("loan_amount");
	}

	public void setLoan_use_term(java.lang.String loan_use_term) {
		set("loan_use_term", loan_use_term);
	}

	public java.lang.String getLoan_use_term() {
		return getStr("loan_use_term");
	}

	public void setApply_remark(java.lang.String apply_remark) {
		set("apply_remark", apply_remark);
	}

	public java.lang.String getApply_remark() {
		return getStr("apply_remark");
	}

	public void setPlatform_remark(java.lang.String platform_remark) {
		set("platform_remark", platform_remark);
	}

	public java.lang.String getPlatform_remark() {
		return getStr("platform_remark");
	}

	public void setAccept_time(java.util.Date accept_time) {
		set("accept_time", accept_time);
	}

	public java.util.Date getAccept_time() {
		return get("accept_time");
	}

	public void setCollection_time(java.util.Date collection_time) {
		set("collection_time", collection_time);
	}

	public java.util.Date getCollection_time() {
		return get("collection_time");
	}

	public void setSubmit_time(java.util.Date submit_time) {
		set("submit_time", submit_time);
	}

	public java.util.Date getSubmit_time() {
		return get("submit_time");
	}

	public void setApproval_time(java.util.Date approval_time) {
		set("approval_time", approval_time);
	}

	public java.util.Date getApproval_time() {
		return get("approval_time");
	}

	public void setLending_time(java.util.Date lending_time) {
		set("lending_time", lending_time);
	}

	public java.util.Date getLending_time() {
		return get("lending_time");
	}

	public void setPass_time(java.util.Date pass_time) {
		set("pass_time", pass_time);
	}

	public java.util.Date getPass_time() {
		return get("pass_time");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
