package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoanInfo<M extends BaseLoanInfo<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setLoan_id(java.lang.Integer loan_id) {
		set("loan_id", loan_id);
	}

	public java.lang.Integer getLoan_id() {
		return getInt("loan_id");
	}

	public void setBt_code(java.lang.String bt_code) {
		set("bt_code", bt_code);
	}

	public java.lang.String getBt_code() {
		return getStr("bt_code");
	}

	public void setLoan_code(java.lang.String loan_code) {
		set("loan_code", loan_code);
	}

	public java.lang.String getLoan_code() {
		return getStr("loan_code");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return getStr("tags");
	}

	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}

	public java.lang.String getLogo() {
		return getStr("logo");
	}

	public void setLoan_plate(java.lang.String loan_plate) {
		set("loan_plate", loan_plate);
	}

	public java.lang.String getLoan_plate() {
		return getStr("loan_plate");
	}

	public void setLoan_use_type(java.lang.String loan_use_type) {
		set("loan_use_type", loan_use_type);
	}

	public java.lang.String getLoan_use_type() {
		return getStr("loan_use_type");
	}

	public void setLoan_term_upper(java.lang.Integer loan_term_upper) {
		set("loan_term_upper", loan_term_upper);
	}

	public java.lang.Integer getLoan_term_upper() {
		return getInt("loan_term_upper");
	}

	public void setLoan_term_lower(java.lang.Integer loan_term_lower) {
		set("loan_term_lower", loan_term_lower);
	}

	public java.lang.Integer getLoan_term_lower() {
		return getInt("loan_term_lower");
	}

	public void setLoan_rate_upper(java.math.BigDecimal loan_rate_upper) {
		set("loan_rate_upper", loan_rate_upper);
	}

	public java.math.BigDecimal getLoan_rate_upper() {
		return get("loan_rate_upper");
	}

	public void setLoan_rate_lower(java.math.BigDecimal loan_rate_lower) {
		set("loan_rate_lower", loan_rate_lower);
	}

	public java.math.BigDecimal getLoan_rate_lower() {
		return get("loan_rate_lower");
	}

	public void setLoan_amount_upper(java.math.BigDecimal loan_amount_upper) {
		set("loan_amount_upper", loan_amount_upper);
	}

	public java.math.BigDecimal getLoan_amount_upper() {
		return get("loan_amount_upper");
	}

	public void setLoan_amount_lower(java.math.BigDecimal loan_amount_lower) {
		set("loan_amount_lower", loan_amount_lower);
	}

	public java.math.BigDecimal getLoan_amount_lower() {
		return get("loan_amount_lower");
	}

	public void setLoan_desc(java.lang.String loan_desc) {
		set("loan_desc", loan_desc);
	}

	public java.lang.String getLoan_desc() {
		return getStr("loan_desc");
	}

	public void setApply_condition(java.lang.String apply_condition) {
		set("apply_condition", apply_condition);
	}

	public java.lang.String getApply_condition() {
		return getStr("apply_condition");
	}

	public void setApply_need_materials(java.lang.String apply_need_materials) {
		set("apply_need_materials", apply_need_materials);
	}

	public java.lang.String getApply_need_materials() {
		return getStr("apply_need_materials");
	}

	public void setApply_need_item(java.lang.String apply_need_item) {
		set("apply_need_item", apply_need_item);
	}

	public java.lang.String getApply_need_item() {
		return getStr("apply_need_item");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return getStr("source");
	}

	public void setIs_recom(java.lang.String is_recom) {
		set("is_recom", is_recom);
	}

	public java.lang.String getIs_recom() {
		return getStr("is_recom");
	}

	public void setOrder_num(java.lang.Integer order_num) {
		set("order_num", order_num);
	}

	public java.lang.Integer getOrder_num() {
		return getInt("order_num");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
