package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebNewsInfo<M extends BaseWebNewsInfo<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setNi_id(java.lang.Integer ni_id) {
		set("ni_id", ni_id);
	}

	public java.lang.Integer getNi_id() {
		return getInt("ni_id");
	}

	public void setNp_code(java.lang.String np_code) {
		set("np_code", np_code);
	}

	public java.lang.String getNp_code() {
		return getStr("np_code");
	}

	public void setNi_code(java.lang.String ni_code) {
		set("ni_code", ni_code);
	}

	public java.lang.String getNi_code() {
		return getStr("ni_code");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}

	public java.lang.String getLogo() {
		return getStr("logo");
	}

	public void setPublish_date(java.util.Date publish_date) {
		set("publish_date", publish_date);
	}

	public java.util.Date getPublish_date() {
		return get("publish_date");
	}

	public void setAuto_publish_date(java.util.Date auto_publish_date) {
		set("auto_publish_date", auto_publish_date);
	}

	public java.util.Date getAuto_publish_date() {
		return get("auto_publish_date");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return getStr("tags");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return getStr("source");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setIs_top(java.lang.String is_top) {
		set("is_top", is_top);
	}

	public java.lang.String getIs_top() {
		return getStr("is_top");
	}

	public void setIs_recom(java.lang.String is_recom) {
		set("is_recom", is_recom);
	}

	public java.lang.String getIs_recom() {
		return getStr("is_recom");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_user(java.lang.String create_user) {
		set("create_user", create_user);
	}

	public java.lang.String getCreate_user() {
		return getStr("create_user");
	}

	public void setModify_user(java.lang.String modify_user) {
		set("modify_user", modify_user);
	}

	public java.lang.String getModify_user() {
		return getStr("modify_user");
	}

}
