package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinancialFund<M extends BaseFinancialFund<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setFp_id(java.lang.Integer fp_id) {
		set("fp_id", fp_id);
	}

	public java.lang.Integer getFp_id() {
		return getInt("fp_id");
	}

	public void setFp_code(java.lang.String fp_code) {
		set("fp_code", fp_code);
	}

	public java.lang.String getFp_code() {
		return getStr("fp_code");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public void setFp_type(java.lang.String fp_type) {
		set("fp_type", fp_type);
	}

	public java.lang.String getFp_type() {
		return getStr("fp_type");
	}

	public void setBt_code(java.lang.String bt_code) {
		set("bt_code", bt_code);
	}

	public java.lang.String getBt_code() {
		return getStr("bt_code");
	}

	public void setFin_code(java.lang.String fin_code) {
		set("fin_code", fin_code);
	}

	public java.lang.String getFin_code() {
		return getStr("fin_code");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setCurrency(java.lang.String currency) {
		set("currency", currency);
	}

	public java.lang.String getCurrency() {
		return getStr("currency");
	}

	public void setFin_nav(java.lang.String fin_nav) {
		set("fin_nav", fin_nav);
	}

	public java.lang.String getFin_nav() {
		return getStr("fin_nav");
	}

	public void setFin_nav_total(java.lang.String fin_nav_total) {
		set("fin_nav_total", fin_nav_total);
	}

	public java.lang.String getFin_nav_total() {
		return getStr("fin_nav_total");
	}

	public void setFin_income(java.lang.String fin_income) {
		set("fin_income", fin_income);
	}

	public java.lang.String getFin_income() {
		return getStr("fin_income");
	}

	public void setFin_income_unit(java.lang.String fin_income_unit) {
		set("fin_income_unit", fin_income_unit);
	}

	public java.lang.String getFin_income_unit() {
		return getStr("fin_income_unit");
	}

	public void setFin_income_rate(java.lang.String fin_income_rate) {
		set("fin_income_rate", fin_income_rate);
	}

	public java.lang.String getFin_income_rate() {
		return getStr("fin_income_rate");
	}

	public void setAmount_min(java.lang.Integer amount_min) {
		set("amount_min", amount_min);
	}

	public java.lang.Integer getAmount_min() {
		return getInt("amount_min");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setShare_count(java.lang.Integer share_count) {
		set("share_count", share_count);
	}

	public java.lang.Integer getShare_count() {
		return getInt("share_count");
	}

	public void setClick_count(java.lang.Integer click_count) {
		set("click_count", click_count);
	}

	public java.lang.Integer getClick_count() {
		return getInt("click_count");
	}

	public void setBuy_count(java.lang.Integer buy_count) {
		set("buy_count", buy_count);
	}

	public java.lang.Integer getBuy_count() {
		return getInt("buy_count");
	}

	public void setIs_recom(java.lang.String is_recom) {
		set("is_recom", is_recom);
	}

	public java.lang.String getIs_recom() {
		return getStr("is_recom");
	}

	public void setOrder_num(java.lang.Integer order_num) {
		set("order_num", order_num);
	}

	public java.lang.Integer getOrder_num() {
		return getInt("order_num");
	}

	public void setPublish_date(java.util.Date publish_date) {
		set("publish_date", publish_date);
	}

	public java.util.Date getPublish_date() {
		return get("publish_date");
	}

	public void setUnder_date(java.util.Date under_date) {
		set("under_date", under_date);
	}

	public java.util.Date getUnder_date() {
		return get("under_date");
	}

	public void setDownload_time(java.util.Date download_time) {
		set("download_time", download_time);
	}

	public java.util.Date getDownload_time() {
		return get("download_time");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
