package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppointmentTime<M extends BaseAppointmentTime<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setSeq_id(java.lang.Integer seq_id) {
		set("seq_id", seq_id);
	}

	public java.lang.Integer getSeq_id() {
		return getInt("seq_id");
	}

	public void setInstitution_type(java.lang.String institution_type) {
		set("institution_type", institution_type);
	}

	public java.lang.String getInstitution_type() {
		return getStr("institution_type");
	}

	public void setInstitution_code(java.lang.String institution_code) {
		set("institution_code", institution_code);
	}

	public java.lang.String getInstitution_code() {
		return getStr("institution_code");
	}

	public void setParam_code(java.lang.String param_code) {
		set("param_code", param_code);
	}

	public java.lang.String getParam_code() {
		return getStr("param_code");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public void setTime_format(java.lang.String time_format) {
		set("time_format", time_format);
	}

	public java.lang.String getTime_format() {
		return getStr("time_format");
	}

	public void setStart_time(java.lang.String start_time) {
		set("start_time", start_time);
	}

	public java.lang.String getStart_time() {
		return getStr("start_time");
	}

	public void setEnd_time(java.lang.String end_time) {
		set("end_time", end_time);
	}

	public java.lang.String getEnd_time() {
		return getStr("end_time");
	}

	public void setBusiness_stat(java.lang.String business_stat) {
		set("business_stat", business_stat);
	}

	public java.lang.String getBusiness_stat() {
		return getStr("business_stat");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
