package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebLinks<M extends BaseWebLinks<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setLinks_id(java.lang.Integer links_id) {
		set("links_id", links_id);
	}

	public java.lang.Integer getLinks_id() {
		return getInt("links_id");
	}

	public void setLinks_code(java.lang.String links_code) {
		set("links_code", links_code);
	}

	public java.lang.String getLinks_code() {
		return getStr("links_code");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public void setLinks_name(java.lang.String links_name) {
		set("links_name", links_name);
	}

	public java.lang.String getLinks_name() {
		return getStr("links_name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}

	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_user(java.lang.String create_user) {
		set("create_user", create_user);
	}

	public java.lang.String getCreate_user() {
		return getStr("create_user");
	}

	public void setModify_user(java.lang.String modify_user) {
		set("modify_user", modify_user);
	}

	public java.lang.String getModify_user() {
		return getStr("modify_user");
	}

}
