package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserBankcard<M extends BaseUserBankcard<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setUbc_id(java.lang.Integer ubc_id) {
		set("ubc_id", ubc_id);
	}

	public java.lang.Integer getUbc_id() {
		return getInt("ubc_id");
	}

	public void setUser_id(java.lang.Integer user_id) {
		set("user_id", user_id);
	}

	public java.lang.Integer getUser_id() {
		return getInt("user_id");
	}

	public void setUbr_id(java.lang.Integer ubr_id) {
		set("ubr_id", ubr_id);
	}

	public java.lang.Integer getUbr_id() {
		return getInt("ubr_id");
	}

	public void setBt_code(java.lang.String bt_code) {
		set("bt_code", bt_code);
	}

	public java.lang.String getBt_code() {
		return getStr("bt_code");
	}

	public void setBankcard_holder(java.lang.String bankcard_holder) {
		set("bankcard_holder", bankcard_holder);
	}

	public java.lang.String getBankcard_holder() {
		return getStr("bankcard_holder");
	}

	public void setBankcard_no(java.lang.String bankcard_no) {
		set("bankcard_no", bankcard_no);
	}

	public java.lang.String getBankcard_no() {
		return getStr("bankcard_no");
	}

	public void setIs_password(java.lang.String is_password) {
		set("is_password", is_password);
	}

	public java.lang.String getIs_password() {
		return getStr("is_password");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setEffect_time(java.util.Date effect_time) {
		set("effect_time", effect_time);
	}

	public java.util.Date getEffect_time() {
		return get("effect_time");
	}

	public void setFrozen_time(java.util.Date frozen_time) {
		set("frozen_time", frozen_time);
	}

	public java.util.Date getFrozen_time() {
		return get("frozen_time");
	}

	public void setUnfrozen_time(java.util.Date unfrozen_time) {
		set("unfrozen_time", unfrozen_time);
	}

	public java.util.Date getUnfrozen_time() {
		return get("unfrozen_time");
	}

	public void setCancel_time(java.util.Date cancel_time) {
		set("cancel_time", cancel_time);
	}

	public java.util.Date getCancel_time() {
		return get("cancel_time");
	}

	public void setRisk_level(java.lang.String risk_level) {
		set("risk_level", risk_level);
	}

	public java.lang.String getRisk_level() {
		return getStr("risk_level");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

	public void setIs_signing(java.lang.String is_signing) {
		set("is_signing", is_signing);
	}

	public java.lang.String getIs_signing() {
		return getStr("is_signing");
	}

	public void setNosecret_sign_code(java.lang.String nosecret_sign_code) {
		set("nosecret_sign_code", nosecret_sign_code);
	}

	public java.lang.String getNosecret_sign_code() {
		return getStr("nosecret_sign_code");
	}

	public void setIs_nosecret_sign(java.lang.String is_nosecret_sign) {
		set("is_nosecret_sign", is_nosecret_sign);
	}

	public java.lang.String getIs_nosecret_sign() {
		return getStr("is_nosecret_sign");
	}

	public void setNosecret_sign_reamt(java.math.BigDecimal nosecret_sign_reamt) {
		set("nosecret_sign_reamt", nosecret_sign_reamt);
	}

	public java.math.BigDecimal getNosecret_sign_reamt() {
		return get("nosecret_sign_reamt");
	}

	public void setSignacno(java.lang.String signacno) {
		set("signAcNo", signacno);
	}

	public java.lang.String getSignacno() {
		return getStr("signAcNo");
	}

}
