package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBankBankcardTradelog<M extends BaseBankBankcardTradelog<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setSeq_id(java.lang.Integer seq_id) {
		set("seq_id", seq_id);
	}

	public java.lang.Integer getSeq_id() {
		return getInt("seq_id");
	}

	public void setUser_id(java.lang.Integer user_id) {
		set("user_id", user_id);
	}

	public java.lang.Integer getUser_id() {
		return getInt("user_id");
	}

	public void setUbc_id(java.lang.Integer ubc_id) {
		set("ubc_id", ubc_id);
	}

	public java.lang.Integer getUbc_id() {
		return getInt("ubc_id");
	}

	public void setBt_code(java.lang.String bt_code) {
		set("bt_code", bt_code);
	}

	public java.lang.String getBt_code() {
		return getStr("bt_code");
	}

	public void setTrade_seq(java.lang.String trade_seq) {
		set("trade_seq", trade_seq);
	}

	public java.lang.String getTrade_seq() {
		return getStr("trade_seq");
	}

	public void setBank_card_no(java.lang.String bank_card_no) {
		set("bank_card_no", bank_card_no);
	}

	public java.lang.String getBank_card_no() {
		return getStr("bank_card_no");
	}

	public void setBind_card_no(java.lang.String bind_card_no) {
		set("bind_card_no", bind_card_no);
	}

	public java.lang.String getBind_card_no() {
		return getStr("bind_card_no");
	}

	public void setTrade_type(java.lang.String trade_type) {
		set("trade_type", trade_type);
	}

	public java.lang.String getTrade_type() {
		return getStr("trade_type");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setCurrency(java.lang.String currency) {
		set("currency", currency);
	}

	public java.lang.String getCurrency() {
		return getStr("currency");
	}

	public void setApply_time(java.util.Date apply_time) {
		set("apply_time", apply_time);
	}

	public java.util.Date getApply_time() {
		return get("apply_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setFinish_time(java.util.Date finish_time) {
		set("finish_time", finish_time);
	}

	public java.util.Date getFinish_time() {
		return get("finish_time");
	}

	public void setInvalid_time(java.util.Date invalid_time) {
		set("invalid_time", invalid_time);
	}

	public java.util.Date getInvalid_time() {
		return get("invalid_time");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
