package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManagepointBank<M extends BaseManagepointBank<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setMb_id(java.lang.Integer mb_id) {
		set("mb_id", mb_id);
	}

	public java.lang.Integer getMb_id() {
		return getInt("mb_id");
	}

	public void setMp_code(java.lang.String mp_code) {
		set("mp_code", mp_code);
	}

	public java.lang.String getMp_code() {
		return getStr("mp_code");
	}

	public void setBt_code(java.lang.String bt_code) {
		set("bt_code", bt_code);
	}

	public java.lang.String getBt_code() {
		return getStr("bt_code");
	}

	public void setBank_code(java.lang.String bank_code) {
		set("bank_code", bank_code);
	}

	public java.lang.String getBank_code() {
		return getStr("bank_code");
	}

	public void setIs_open_account(java.lang.String is_open_account) {
		set("is_open_account", is_open_account);
	}

	public java.lang.String getIs_open_account() {
		return getStr("is_open_account");
	}

	public void setStart_date(java.util.Date start_date) {
		set("start_date", start_date);
	}

	public java.util.Date getStart_date() {
		return get("start_date");
	}

	public void setEnd_date(java.util.Date end_date) {
		set("end_date", end_date);
	}

	public java.util.Date getEnd_date() {
		return get("end_date");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
