package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserWithdrawAppointment<M extends BaseUserWithdrawAppointment<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setUwa_id(java.lang.Integer uwa_id) {
		set("uwa_id", uwa_id);
	}

	public java.lang.Integer getUwa_id() {
		return getInt("uwa_id");
	}

	public void setUser_id(java.lang.Integer user_id) {
		set("user_id", user_id);
	}

	public java.lang.Integer getUser_id() {
		return getInt("user_id");
	}

	public void setMp_code(java.lang.String mp_code) {
		set("mp_code", mp_code);
	}

	public java.lang.String getMp_code() {
		return getStr("mp_code");
	}

	public void setTrue_name(java.lang.String true_name) {
		set("true_name", true_name);
	}

	public java.lang.String getTrue_name() {
		return getStr("true_name");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setAm_date(java.util.Date am_date) {
		set("am_date", am_date);
	}

	public java.util.Date getAm_date() {
		return get("am_date");
	}

	public void setAccept_time(java.util.Date accept_time) {
		set("accept_time", accept_time);
	}

	public java.util.Date getAccept_time() {
		return get("accept_time");
	}

	public void setRefuse_time(java.util.Date refuse_time) {
		set("refuse_time", refuse_time);
	}

	public java.util.Date getRefuse_time() {
		return get("refuse_time");
	}

	public void setCancel_time(java.util.Date cancel_time) {
		set("cancel_time", cancel_time);
	}

	public java.util.Date getCancel_time() {
		return get("cancel_time");
	}

	public void setMp_opt(java.lang.Integer mp_opt) {
		set("mp_opt", mp_opt);
	}

	public java.lang.Integer getMp_opt() {
		return getInt("mp_opt");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
