package com.bankwel.phjf_admin.common.model.core.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserLoanApply<M extends BaseUserLoanApply<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setUlp_id(java.lang.Integer ulp_id) {
		set("ulp_id", ulp_id);
	}

	public java.lang.Integer getUlp_id() {
		return getInt("ulp_id");
	}

	public void setUser_id(java.lang.Integer user_id) {
		set("user_id", user_id);
	}

	public java.lang.Integer getUser_id() {
		return getInt("user_id");
	}

	public void setLoan_code(java.lang.String loan_code) {
		set("loan_code", loan_code);
	}

	public java.lang.String getLoan_code() {
		return getStr("loan_code");
	}

	public void setTrue_name(java.lang.String true_name) {
		set("true_name", true_name);
	}

	public java.lang.String getTrue_name() {
		return getStr("true_name");
	}

	public void setId_type(java.lang.String id_type) {
		set("id_type", id_type);
	}

	public java.lang.String getId_type() {
		return getStr("id_type");
	}

	public void setId_num(java.lang.String id_num) {
		set("id_num", id_num);
	}

	public java.lang.String getId_num() {
		return getStr("id_num");
	}

	public void setMobilephone(java.lang.String mobilephone) {
		set("mobilephone", mobilephone);
	}

	public java.lang.String getMobilephone() {
		return getStr("mobilephone");
	}

	public void setLoan_use_type(java.lang.String loan_use_type) {
		set("loan_use_type", loan_use_type);
	}

	public java.lang.String getLoan_use_type() {
		return getStr("loan_use_type");
	}

	public void setLoan_amount(java.lang.String loan_amount) {
		set("loan_amount", loan_amount);
	}

	public java.lang.String getLoan_amount() {
		return getStr("loan_amount");
	}

	public void setLoan_use_term(java.lang.String loan_use_term) {
		set("loan_use_term", loan_use_term);
	}

	public java.lang.String getLoan_use_term() {
		return getStr("loan_use_term");
	}

	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}

	public java.lang.String getLat() {
		return getStr("lat");
	}

	public void setLng(java.lang.String lng) {
		set("lng", lng);
	}

	public java.lang.String getLng() {
		return getStr("lng");
	}

	public void setCash_loan_type(java.lang.String cash_loan_type) {
		set("cash_loan_type", cash_loan_type);
	}

	public java.lang.String getCash_loan_type() {
		return getStr("cash_loan_type");
	}

	public void setCash_loan_term(java.lang.String cash_loan_term) {
		set("cash_loan_term", cash_loan_term);
	}

	public java.lang.String getCash_loan_term() {
		return getStr("cash_loan_term");
	}

	public void setCash_receipt_card(java.lang.String cash_receipt_card) {
		set("cash_receipt_card", cash_receipt_card);
	}

	public java.lang.String getCash_receipt_card() {
		return getStr("cash_receipt_card");
	}

	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}

	public java.lang.String getProfession() {
		return getStr("profession");
	}

	public void setWages_paytype(java.lang.String wages_paytype) {
		set("wages_paytype", wages_paytype);
	}

	public java.lang.String getWages_paytype() {
		return getStr("wages_paytype");
	}

	public void setWork_years(java.lang.String work_years) {
		set("work_years", work_years);
	}

	public java.lang.String getWork_years() {
		return getStr("work_years");
	}

	public void setSalary_bank(java.math.BigDecimal salary_bank) {
		set("salary_bank", salary_bank);
	}

	public java.math.BigDecimal getSalary_bank() {
		return get("salary_bank");
	}

	public void setRunning(java.math.BigDecimal running) {
		set("running", running);
	}

	public java.math.BigDecimal getRunning() {
		return get("running");
	}

	public void setIncome_cash(java.math.BigDecimal income_cash) {
		set("income_cash", income_cash);
	}

	public java.math.BigDecimal getIncome_cash() {
		return get("income_cash");
	}

	public void setOperation_years(java.lang.String operation_years) {
		set("operation_years", operation_years);
	}

	public java.lang.String getOperation_years() {
		return getStr("operation_years");
	}

	public void setReg_loc_type(java.lang.String reg_loc_type) {
		set("reg_loc_type", reg_loc_type);
	}

	public java.lang.String getReg_loc_type() {
		return getStr("reg_loc_type");
	}

	public void setIs_hava_bl(java.lang.String is_hava_bl) {
		set("is_hava_bl", is_hava_bl);
	}

	public java.lang.String getIs_hava_bl() {
		return getStr("is_hava_bl");
	}

	public void setSalary_cash(java.math.BigDecimal salary_cash) {
		set("salary_cash", salary_cash);
	}

	public java.math.BigDecimal getSalary_cash() {
		return get("salary_cash");
	}

	public void setIncome_public(java.math.BigDecimal income_public) {
		set("income_public", income_public);
	}

	public java.math.BigDecimal getIncome_public() {
		return get("income_public");
	}

	public void setIs_have_loc_gjj(java.lang.String is_have_loc_gjj) {
		set("is_have_loc_gjj", is_have_loc_gjj);
	}

	public java.lang.String getIs_have_loc_gjj() {
		return getStr("is_have_loc_gjj");
	}

	public void setIs_have_loc_ss(java.lang.String is_have_loc_ss) {
		set("is_have_loc_ss", is_have_loc_ss);
	}

	public java.lang.String getIs_have_loc_ss() {
		return getStr("is_have_loc_ss");
	}

	public void setHouse_type(java.lang.String house_type) {
		set("house_type", house_type);
	}

	public java.lang.String getHouse_type() {
		return getStr("house_type");
	}

	public void setIs_have_car(java.lang.String is_have_car) {
		set("is_have_car", is_have_car);
	}

	public java.lang.String getIs_have_car() {
		return getStr("is_have_car");
	}

	public void setCredit_situation(java.lang.String credit_situation) {
		set("credit_situation", credit_situation);
	}

	public java.lang.String getCredit_situation() {
		return getStr("credit_situation");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setPass_time(java.util.Date pass_time) {
		set("pass_time", pass_time);
	}

	public java.util.Date getPass_time() {
		return get("pass_time");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
