package com.bankwel.phjf_website.client;

import com.bankwel.framework.core.urls.InterfaceAccess;

/**
 * Generated by su_ln on 2016/2/5.
 */
public class HttpInterConstants {

    public static final InterfaceAccess Img_Upload_INF = new InterfaceAccess("WX_payNotify_INF", "http://121.199.13.119:18121/BankwelImg/imgUpdater/upload64");


}
