package com.bankwel.phjf_website.common.model;

import com.bankwel.framework.core.encrypt.AES;
import com.jfinal.kit.PathKit;
import com.jfinal.kit.PropKit;
import com.jfinal.plugin.activerecord.generator.Generator;
import com.jfinal.plugin.druid.DruidPlugin;
import com.bankwel.framework.support.jfinal.PublicMappingKitGenerator;
import com.bankwel.framework.support.jfinal.PublicMetaBuilder;

/**
 * Generated by su_ln on 2016/2/19.
 */
public class PhjfWebSiteModelCreater {

    public static AES aes = AES.getInstance("BfjDbKeyPass2017");

    /**
     * Main方法
     * @param args
     */
    public static void main(String[] args){
        createFrontier();
    }

    public static void createFrontier(){
        PropKit.use("config.properties");
//        System.out.println(PropKit.get("public.db.url"));
        DruidPlugin DBPlugin = new DruidPlugin(PropKit.get("public.db.url"), PropKit.get("public.db.username"), aes.decode(PropKit.get("public.db.password")));
//        DruidPlugin DBPlugin = new DruidPlugin(PropKit.get("public.db.url"), "root", "admin");
        DBPlugin.start();

        String basePack = "com.bankwel.phjf_website.common.model.website.base";
        String modelPack = "com.bankwel.phjf_website.common.model.website";
        String baseOutPackDir  = PathKit.getRootClassPath()+"/../../src/main/java/com/bankwel/phjf_website/common/model/website/base";
        String modelOutPackDir = PathKit.getRootClassPath()+"/../../src/main/java/com/bankwel/phjf_website/common/model/website/";
        Generator g = new Generator(DBPlugin.getDataSource(),basePack,baseOutPackDir,modelPack,modelOutPackDir);

        PublicMetaBuilder mb = new PublicMetaBuilder(DBPlugin.getDataSource());
        mb.addIncludedTable("phjf_web_nav");//
        mb.addIncludedTable("phjf_web_banner");//
        mb.addIncludedTable("phjf_web_news_plate");//
        mb.addIncludedTable("phjf_web_news_info");//
        mb.addIncludedTable("phjf_web_app_download_info");//
        mb.addIncludedTable("phjf_web_partner");//
        mb.addIncludedTable("phjf_web_links");//
        mb.addIncludedTable("phjf_web_about_us");//
        mb.addIncludedTable("phjf_news_article");//
        mb.addIncludedTable("phjf_bank_type");//
        mb.addIncludedTable("phjf_bank_info");//
        mb.addIncludedTable("phjf_bank_atm");//
        mb.addIncludedTable("phjf_managepoint_info");//
        mb.addIncludedTable("phjf_app_info");//
//        mb.addIncludedTable("");//
//        mb.addIncludedTable("");//
//        mb.addIncludedTable("");//
        g.setMetaBuilder(mb);
        g.setMappingKitGenerator(new PublicMappingKitGenerator(modelPack, modelOutPackDir,"_PhjfMappingKit"));
        g.setGenerateDaoInModel(true);
        g.setGenerateDaoInModel(true);
        g.setRemovedTableNamePrefixes("phjf_");
        g.generate();
    }

}
