package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.phjf_admin.common.model.core.base.BaseBankDepositInfo;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheBankDepositInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BankDepositInfo extends CacheBankDepositInfo<BankDepositInfo> {
	public static final BankDepositInfo dao = new BankDepositInfo().dao();
}
