package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.excep.MsgBusinessException;
import com.bankwel.framework.core.kit.JFinalDbKit;
import com.bankwel.framework.core.kit.PageKit;
import com.bankwel.phjf_admin.common.constants.admin.AdminConstants;
import com.bankwel.phjf_admin.common.model.core.base.BaseNewsArticle;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheNewsArticle;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import org.apache.commons.lang3.tuple.Pair;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsArticle extends CacheNewsArticle<NewsArticle> {
	public static final NewsArticle dao = new NewsArticle().dao();
	/**
	 * 新增或修改新闻文章
	 * @param opt
	 * @return
	 */
	public NewsArticle saveOrUpdate(AuthOperator opt) throws MsgBusinessException{
		this.checkModelItem();
		if (F.validate.isNotEmpty(this.getNa_id()+"")&&!(this.getNa_id().equals(0))){
			this.setModify_opt(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			if(F.validate.isEmpty(this.getIs_show())){
				this.setIs_show("Y");
			}
			this.update();
		} else {
			if (F.validate.isEmpty(this.getArticle_code())){
				this.setArticle_code(SysSeq.dao.generatorNewsCode());
			}
			if(F.validate.isEmpty(this.getIs_recom())){
				this.setIs_recom("N");
			}
			if(F.validate.isEmpty(this.getIs_top())){
				this.setIs_top("N");
			}
			if(F.validate.isEmpty(this.getIs_banner())){
				this.setIs_banner("N");
			}
			this.setSeq_uuid(UUID.randomUUID().toString());
			this.setIs_show("Y");
			this.setStatus("1");
			this.setCreate_opt(opt.getSeq_id()+"");
			this.setCreate_time(new Date());
			this.setModify_opt(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			this.save();
		}
		flashCatch(this);
		return this;
	}
	public void checkModelItem(){
		this.checkPlate_code("新闻文章版块编码");
		this.checkArticle_code("新闻文章内部编码");
		this.checkLanguage("语言");
		this.checkTitle("新闻文章标题");
		this.checkLogo("新闻文章LOGO地址");
		this.checkPublish_date("新闻文章发表日期");
		this.checkAuto_publish_date("新闻文章自动发布日期");
		this.checkTags("新闻文章标签");
		this.checkSource("新闻文章来源");
		this.checkSource_url("新闻文章来源地址");
		this.checkContent("新闻文章内容");
		this.checkShare_count("分享次数");
		this.checkClick_count("点击次数");
		this.checkBanner_logo("轮播图");
		this.checkIs_top("是否置顶");
		this.checkIs_recom("是否推荐");
		this.checkRemark("备注");
	}

	/**
	 * 获取新闻文章列表
	 * @param plate_name
	 * @param title
	 * @param publish_date
	 * @param language
	 * @param status
	 * @param page
	 * @return
	 */
	public Pair<List<Record>,PageKit<Record>> queryNewsArticleByPage(String plate_name,String title,String publish_date, String language, String status, PageKit page){
		String sql = "select article.seq_uuid," +
				"            article.na_id," +
				"            article.plate_code," +
				"            article.article_code," +
				"            article.title," +
				"            article.language," +
				"            article.publish_date," +
				"            article.tags," +
				"            article.source," +
				"            article.share_count," +
				"            article.click_count," +
				"            article.is_top," +
				"            article.is_recom," +
				"            article.remark," +
				"            article.status," +
				"            article.create_time," +
				"            status.name status_show," +
				"            is_show.name is_show_name," +
				"            is_top.name is_top_show," +
				"            is_recom.name is_recom_show," +
				"            is_banner.name is_banner_show," +
				"            plate.name plate_name" +
				"       from phjf_news_article article" +
				"            left join phjf_news_plate plate on plate.plate_code = article.plate_code and plate.language = article.language" +
				"            left join sys_datalibrary status on status.parent_code = 'sys_articleStatus' and status.code = article.status" +
				"            left join sys_datalibrary is_show on is_show.parent_code = 'sys_isShow' and is_show.code = article.is_show" +
				"            left join sys_datalibrary is_top on is_top.parent_code = 'sys_yesNo' and is_top.code = article.is_top" +
				"            left join sys_datalibrary is_recom on is_recom.parent_code = 'sys_isRecom' and is_recom.code = article.is_recom" +
				"            left join sys_datalibrary is_banner on is_banner.parent_code = 'sys_isBanner' and is_banner.code = article.is_banner" +
				"      where 1=1";
		List params = new ArrayList();
		if (F.validate.isNotEmpty(plate_name)){
			sql += " and (article.plate_code = ? or plate.name LIKE concat('%',?,'%'))";
			params.add(plate_name);
			params.add(plate_name);
		}
		if (F.validate.isNotEmpty(title)){
			sql += " and (article.title LIKE concat('%',?,'%') or article.article_code = ?)";
			params.add(title);
			params.add(title);
		}
		if (F.validate.isNotEmpty(publish_date)){
			sql += " and article.publish_date = ?";
			params.add(publish_date);
		}
		if (F.validate.isNotEmpty(language)){
			sql += " and article.language = ? ";
			params.add(language);
		}
		if (F.validate.isNotEmpty(status)){
			sql += " and article.status = ? ";
			params.add(status);
		}
		sql += " order by article.create_time desc";
		return JFinalDbKit.paginate(Db.use("DBPublic"), page.getNowPage(), page.getRowsPerPage(), sql, params.toArray());
	}

	/**
	 * 通过ID获取新闻文章
	 * @param seq_uuid
	 * @return
	 */
	public NewsArticle findById(String seq_uuid){
		String sql = "select * " +
				"       from phjf_news_article " +
				"      where seq_uuid = ? " +
				"      limit 1";
		NewsArticle data = NewsArticle.dao.use("DBPublic").findFirst(sql,seq_uuid);
		if(F.validate.isEmpty(data)){
			data = new NewsArticle();
		}
		return data;
	}

	/**
	 *通过article_code获取新闻文章
	 * @param article_code
	 * @return
	 */
	public List<NewsArticle> findByArticleCode(String article_code){
		String sql = "select * " +
				"       from phjf_news_article " +
				"      where article_code = ? "+
		        "        and status != 3 ";
		return NewsArticle.dao.use("DBPublic").find(sql,article_code);
	}

	/**
	 *通过文章标题和版块获取新闻文章
	 * @param plate_code
	 * @param title
	 * @return
	 */
	public NewsArticle findByArticleTitle(String plate_code, String title){
		String sql = "select * " +
				"       from phjf_news_article " +
				"      where plate_code = ?" +
				"        and title = ? " +
				"        and status != 3 ";
		NewsArticle data = NewsArticle.dao.use("DBPublic").findFirst(sql,plate_code,title);
		if(F.validate.isEmpty(data)){
			data = new NewsArticle();
		}
		return data;
	}

	/**
	 * 通过plate_code获取新闻文章
	 * @param plate_code
	 * @return
	 */
	public List<NewsArticle> findByPlateCode(String plate_code){
		String sql = "select * " +
				"       from phjf_news_article " +
				"      where plate_code = ? " +
				"        and status !=3" +
				"      limit 1";
		return NewsArticle.dao.use("DBPublic").find(sql,plate_code);
	}

	/**
	 * 修改前判断文章标题是否存在
	 * @param seq_uuid
	 * @param plate_code
	 * @param title
	 * @return
	 */
	public Boolean isHaveArticle(String seq_uuid, String plate_code, String title){
		String sql = "select * " +
				"       from phjf_news_article " +
				"      where seq_uuid != ? " +
				"        and plate_code = ?" +
				"        and title = ?" +
				"        and status !=3" +
				"      limit 1";
		NewsArticle newsArticle = NewsArticle.dao.use("DBPublic").findFirst(sql,seq_uuid,plate_code,title);
		if(F.validate.isEmpty(newsArticle)){
			return false;
		}
		return true;
	}

	/**
	 * 获取语言的中文名
	 * @return
	 */
	public String findLanguage_show(){
		SysDatalibrary library = SysDatalibrary.dao.queryDatalibrary("Phjf", "sys_language", this.getLanguage());
		return library.getName();
	}

	/**
	 * 获取新闻版块
	 * @return
	 */
	public NewsPlate findNewsPlate(){
		NewsPlate newsPlate = NewsPlate.dao.findNewsPlate(this.getPlate_code(), AdminConstants.ZH_SIMP);
		if(F.validate.isEmpty(newsPlate)){
			newsPlate = new NewsPlate();
		}
		return newsPlate;
	}

	/**
	 * 通过code和语言获取新闻文章
	 * @param article_code
	 * @param language
	 * @return
	 */
	public NewsArticle findNewsArticle(String article_code,String language){
		String sql = "select * " +
				"       from phjf_news_article " +
				"      where article_code = ? " +
				"        and language = ?" +
				"        and status !=3" +
				"      limit 1";
		NewsArticle data = NewsArticle.dao.use("DBPublic").findFirst(sql,article_code,language);
		if(F.validate.isEmpty(data)){
			data = new NewsArticle();
		}
		return data;
	}
}
