package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.excep.MsgBusinessException;
import com.bankwel.phjf_admin.common.model.core.base.BasePolicyPlateCity;
import com.bankwel.phjf_baseModel.common.model.phjf.enumKey.ApiNewsPlateEnum;

import java.util.Date;
import java.util.UUID;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PolicyPlateCity extends BasePolicyPlateCity<PolicyPlateCity> {
	public static final PolicyPlateCity dao = new PolicyPlateCity().dao();
	/**
	 * 新增或修改惠民政策版块
	 * @param opt
	 * @return
	 */
	public PolicyPlateCity saveOrUpdate(AuthOperator opt) throws MsgBusinessException {
		this.checkModelItem();
		if (F.validate.isNotEmpty(this.getPpc_id()+"")&&!(this.getPpc_id().equals(0))){
			this.setModify_opt(opt.getSeq_id()+"");
			this.setModify_time(new Date());
            if(F.validate.isEmpty(this.getIs_show())){
                this.setIs_show("Y");
            }
			this.update();
		} else {
			if (F.validate.isEmpty(this.getPlate_code())){
				this.setPlate_code(SysSeq.dao.generatorPolicyPlateCode());
			}
			this.setSeq_uuid(UUID.randomUUID().toString());
			this.setIs_show("Y");
			this.setStatus("1");
			this.setCreate_opt(opt.getSeq_id()+"");
			this.setCreate_time(new Date());
			this.setModify_opt(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			this.save();
		}
//		String key1 =F.strKit.f(ApiNewsPlateEnum.CK_Phjf_Model_NewsPlate_KEY1.getKey(),this.getLanguage());
//		flashCatch(this);
		return this;
	}
	public void checkModelItem() {
//        this.checkOrder_num("板块序号");
	}
	/**
	 * 通过ID获取惠民政策版块
	 * @param seq_uuid
	 * @return
	 */
	public PolicyPlateCity findById(String seq_uuid){
		String sql = "select * " +
				"       from phjf_policy_plate_city " +
				"      where seq_uuid = ? " +
				"      limit 1";
		PolicyPlateCity data = PolicyPlateCity.dao.use("DBPublic").findFirst(sql,seq_uuid);
		if(F.validate.isEmpty(data)){
			data = new PolicyPlateCity();
		}
		return data;
	}
	/**
	 *通过版块code获取惠民政策版块
	 * @return
	 */
	public PolicyPlateCity findByPlateCode(String plate_code){
		String sql = "select * " +
				"       from phjf_policy_plate_city " +
				"      where plate_code = ? " +
				"        and status = 1 ";
		PolicyPlateCity data = PolicyPlateCity.dao.use("DBPublic").findFirst(sql,plate_code);
		if(F.validate.isEmpty(data)){
			data = new PolicyPlateCity();
		}
		return data;
	}

    public PolicyPlateCity findByPlateInfo(String plate_code, String province_id){
        String sql = "select * " +
                "       from phjf_policy_plate_city " +
                "      where plate_code = ? " +
                "        and province_id = ?" +
                "        and status = 1 ";
        PolicyPlateCity data = PolicyPlateCity.dao.use("DBPublic").findFirst(sql,plate_code,province_id);
        if(F.validate.isEmpty(data)){
            data = new PolicyPlateCity();
        }
        return data;
    }
	/**
	 * 修改前判断该惠民政策版块名称是否存在
	 * @param seq_uuid
	 * @return
	 */
	public Boolean isHavePlate(String seq_uuid,String plate_code){
		String sql = "select * " +
				"       from phjf_policy_plate_city " +
				"      where seq_uuid !=? " +
				"        and plate_code = ?" +
				"        and status = 1 ";
		PolicyPlateCity data = PolicyPlateCity.dao.use("DBPublic").findFirst(sql,seq_uuid,plate_code);
		if(F.validate.isEmpty(data)){
			return false;
		}
		return true;
	}

}
