package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.phjf_admin.common.model.core.base.BaseSysAreas;
import com.bankwel.phjf_admin.component.c13webtag.bootstrap.DynamicSelectData;
import com.bankwel.phjf_admin.component.c13webtag.bootstrap.IDynamicSelectData;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheSysAreas;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAreas extends CacheSysAreas<SysAreas> {
	public static final SysAreas dao = new SysAreas().dao();

	/**
	 * 根据城市ID获取区信息
	 * @param city_id
	 * @return
	 */
	public List<IDynamicSelectData> querySelectData(String city_id){
		String sql = "select * " +
				"       from sys_areas " +
				"      where is_show = 'Y' " +
				"        and city_id = ? ";
		List<SysAreas> list = dao.use("DBPublic").find(sql, city_id);
		List<IDynamicSelectData> selectData = new ArrayList<IDynamicSelectData>();
		for (SysAreas area : list){
			IDynamicSelectData sd = new DynamicSelectData();
			sd.setId(area.getArea_id());
			sd.setName(area.getArea());
			selectData.add(sd);
		}
		return selectData;
	}

	/**
	 * 通过ID获取区名
	 * @return
	 */
	public SysAreas findAreaById(String area_id){
		String sql = "select * " +
				"       from sys_areas " +
				"      where area_id = ? " +
				"        and status = 1 ";
		SysAreas area = dao.use("DBPublic").findFirst(sql, area_id);
		if(F.validate.isEmpty(area)){
			area = new SysAreas();
		}
		return area;
	}
}
