package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.util.DataLoader;
import com.bankwel.framework.support.codis.RedisClient;
import com.bankwel.phjf_admin.catchsystem.CatchKeyConst;
import com.bankwel.phjf_admin.common.model.core.base.BaseSysDatalibrary;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheSysDatalibrary;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDatalibrary extends CacheSysDatalibrary<SysDatalibrary> {
	public static final SysDatalibrary dao = new SysDatalibrary().dao();

	/**
	 * 查询数据字典
	 * @param sys_id
	 * @param parentCode
	 */
	public List<SysDatalibrary> querySysDatalibrary(String sys_id, String parentCode){
		String sql = "select * " +
				"       from sys_datalibrary " +
				"      where sys_id = ? " +
				"        and parent_code = ? " +
				"      order by show_order asc ";
		List<SysDatalibrary> dataList = dao.use("DBPublic").find(sql, sys_id, parentCode);
		if(F.validate.isEmpty(dataList)){
			dataList = new ArrayList<SysDatalibrary>();
		}
		return dataList;
	}
	/**
	 * 查询数据字典
	 * @param sys_id
	 * @param parentCode
	 */
	public List<SysDatalibrary> querySysDatalibrarys(final String sys_id, final String language,final String parentCode){
		String sql = "select * " +
				"       from sys_datalibrary " +
				"      where sys_id = ? " +
				"        and language = ? " +
				"        and parent_code = ? ";
		List<SysDatalibrary> dataList = dao.use("DBPublic").find(sql,sys_id,language,parentCode);
		if(F.validate.isEmpty(dataList)){
			dataList = new ArrayList<SysDatalibrary>();
		}
		return dataList;
	}
	/**
	 * 获取字典信息
	 * @param sys_id
	 * @param parentCode
	 * @param code
     * @return
     */
	public SysDatalibrary queryDatalibrary(String sys_id, String parentCode, String code){
		String sql = "select * " +
				"       from sys_datalibrary " +
				"      where sys_id = ? " +
				"        and parent_code = ? " +
				"        and code = ? " +
				"      limit 1 ";
		SysDatalibrary datalibrary = dao.use("DBPublic").findFirst(sql, sys_id, parentCode,code);
		if(F.validate.isEmpty(datalibrary)){
			datalibrary = new SysDatalibrary();
		}
		return datalibrary;
	}
	/**
	 * 获取数据字典
	 * @param language
	 * @param parent_code
	 * @param code
	 * @return
	 */
	public SysDatalibrary findSysDatalibrary(final String language, final String parent_code, final String code){
		String sql = "select * " +
				"       from sys_datalibrary " +
				"      where language = ? " +
				"        and parent_code = ? " +
				"        and code = ? ";
		SysDatalibrary date = dao.use("DBPublic").findFirst(sql,language, parent_code, code);
		if (F.validate.isEmpty(date)){
			date = new SysDatalibrary();
		}
		return date;
	}

	/**
	 * 检验业务对象是否为空
	 * @return
	 */
	public boolean isEmpty(){
		if(F.validate.isEmpty(this.getSeq_uuid())){
			return true;
		}
		return false;
	}
}
