package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.phjf_admin.common.model.core.base.BaseSysProvinces;
import com.bankwel.phjf_admin.component.c13webtag.bootstrap.DynamicSelectData;
import com.bankwel.phjf_admin.component.c13webtag.bootstrap.IDynamicSelectData;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheSysProvinces;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysProvinces extends CacheSysProvinces<SysProvinces> {
	public static final SysProvinces dao = new SysProvinces().dao();

	public List<IDynamicSelectData> querySelectData(){
		String sql = "select * from sys_provinces where is_show = 'Y' ";
		List<SysProvinces> list = dao.use("DBPublic").find(sql);
		List<IDynamicSelectData> selectData = new ArrayList<IDynamicSelectData>();
		for (SysProvinces provinces : list){
			IDynamicSelectData sd = new DynamicSelectData();
			sd.setId(provinces.getProvince_id());
			sd.setName(provinces.getProvince());
			selectData.add(sd);
		}
		return selectData;
	}

	public SysProvinces findProvinceById(String province_id){
		String sql = "select * " +
				"       from sys_provinces " +
				"      where province_id = ? " +
				"        and status = 1 ";
		SysProvinces province = dao.use("DBPublic").findFirst(sql, province_id);
		if(F.validate.isEmpty(province)){
			province = new SysProvinces();
		}
		return province;
	}
	/**
	 * 查询数据字典
	 */
	public List<SysProvinces> queryProvinceById(){
		String sql = "select * " +
				"       from sys_provinces " +
				"      where status = 1 " +
				"        and is_show = 'Y'" ;
		List<SysProvinces> dataList = dao.use("DBPublic").find(sql);
		if(F.validate.isEmpty(dataList)){
			dataList = new ArrayList<SysProvinces>();
		}
		return dataList;
	}
}
