package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.kit.JFinalDbKit;
import com.bankwel.framework.core.kit.PageKit;
import com.bankwel.phjf_admin.common.model.core.base.BaseUserFeedback;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheUserFeedback;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import org.apache.commons.lang3.tuple.Pair;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFeedback extends CacheUserFeedback<UserFeedback> {
	public static final UserFeedback dao = new UserFeedback().dao();

	/**
	 * 查询
	 * @param user_name
	 * @param name
	 * @param page
	 * @return
	 */
	public Pair<List<Record>, PageKit<Record>> queryUserFeedbackByPage(String user_name, String name, PageKit page){
		String sql = "select userInfo.true_name " +
				"            , userInfo.mobilephone " +
				"            , feedback.content " +
				"            , feedback.recontent " +
				"            , resultStatus.name result_status_show " +
				"            , feedback.create_time " +
				"       from phjf_user_feedback feedback " +
				"            left join phjf_user_info userInfo on userInfo.user_id = feedback.user_id " +
				"            left join sys_datalibrary resultStatus on resultStatus.parent_code = 'result_status' and resultStatus.code = feedback.result_status " +
				"      where 1 = 1 ";
		List params = new ArrayList();
		if (F.validate.isNotEmpty(user_name)){
			sql += " and userInfo.user_name like concat('%',?,'%') ";
			params.add(user_name);
		}
		if (F.validate.isNotEmpty(name)){
			sql += " and userInfo.true_name like concat('%',?,'%') ";
			params.add(name);
		}

		sql += " order by feedback.create_time desc ";
		return JFinalDbKit.paginate(Db.use("DBPublic"), page.getNowPage(), page.getRowsPerPage(), sql, params.toArray());

	}
}
