package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.phjf_baseModel.common.model.phjf.CacheUserLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLoginLog extends CacheUserLoginLog<UserLoginLog> {
	public static final UserLoginLog dao = new UserLoginLog().dao();
}
