package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.kit.JFinalDbKit;
import com.bankwel.framework.core.kit.PageKit;
import com.bankwel.phjf_admin.common.model.core.base.BaseUserLoanApply;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheUserLoanApply;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import org.apache.commons.lang3.tuple.Pair;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLoanApply extends CacheUserLoanApply<UserLoanApply> {
	public static final UserLoanApply dao = new UserLoanApply().dao();

	/**
	 * 查询
	 * @param mobilephone
	 * @param name
	 * @param loan_type
	 * @param page
     * @return
     */
	public Pair<List<Record>, PageKit<Record>> queryUserLoanByPage(String mobilephone, String name, String loan_type, PageKit page){
		String sql = "select loanApply.true_name " +
				"            , userInfo.mobilephone " +
				"            , loanType.name loan_type_show " +
				"            , loanStatus.name loan_status_show " +
				"            , isShow.name is_show " +
				"            , loanApply.create_time " +
				"            , loanApply.seq_uuid " +
				"            , loanApply.user_id " +
				"            , loanApply.loan_amount  " +
				"            , loanApply.loan_use_term  " +
				"       from phjf_user_loan_apply loanApply " +
				"            left join phjf_user_info userInfo on userInfo.user_id = loanApply.user_id " +
				"            left join sys_datalibrary loanType on loanType.parent_code = 'loan_useType' and loanType.code = loanApply.loan_use_type " +
				"            left join sys_datalibrary loanStatus on loanStatus.parent_code = 'loan_user_applyStatus' and loanStatus.code = loanApply.status " +
				"            left join sys_datalibrary isShow on isShow.parent_code = 'sys_isShow' and isShow.code = loanApply.is_show " +
				"      where loanApply.status IN('1','2','3','4','5','6','9') and 1 = 1 ";
		List params = new ArrayList();
		if (F.validate.isNotEmpty(mobilephone)){
			sql += " and userInfo.mobilephone like concat('%',?,'%') ";
			params.add(mobilephone);
		}
		if (F.validate.isNotEmpty(name)){
			sql += " and loanApply.true_name like concat('%',?,'%') ";
			params.add(name);
		}
		if (F.validate.isNotEmpty(loan_type)){
			sql += " and loanApply.loan_type = ? ";
			params.add(loan_type);
		}
		sql += " order by loanApply.create_time desc ";
		return JFinalDbKit.paginate(Db.use("DBPublic"), page.getNowPage(), page.getRowsPerPage(), sql, params.toArray());

	}

	/**
	 * 查询
	 * @param seq_uuid
	 * @return
	 */
	public UserLoanApply findBySeqUuid(String seq_uuid){
		String sql = " select * " +
				"        from phjf_user_loan_apply " +
				"       where seq_uuid = ? " +
				"        and  is_show = 'Y' " +
				"      limit 1 ";
		UserLoanApply data = UserLoanApply.dao.use("DBPublic").findFirst(sql,seq_uuid);
		if(F.validate.isEmpty(data)){
			data = new UserLoanApply();
		}
		return data;
	}
}
