package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.excep.MsgBusinessException;
import com.bankwel.framework.core.kit.JFinalDbKit;
import com.bankwel.framework.core.kit.PageKit;
import com.bankwel.phjf_admin.common.model.core.base.BaseWebAppDownloadInfo;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheWebAppDownloadInfo;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import org.apache.commons.lang3.tuple.Pair;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebAppDownloadInfo extends CacheWebAppDownloadInfo<WebAppDownloadInfo> {
	public static final WebAppDownloadInfo dao = new WebAppDownloadInfo().dao();
	/**
	 * 新增或修改广告位
	 * @param opt
	 * @return
	 */
	public WebAppDownloadInfo saveOrUpdate(AuthOperator opt) throws MsgBusinessException{
		this.checkModelItem();
		if (F.validate.isNotEmpty(this.getAdi_id()+"")&&!(this.getAdi_id().equals(0))){
			this.setModify_user(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			if(F.validate.isEmpty(this.getIs_show())){
				this.setIs_show("Y");
			}
			this.update();
		} else {
			if (F.validate.isEmpty(this.getAdi_code())){
				this.setAdi_code(SysSeq.dao.generatorWebAdiCode());
			}
			this.setSeq_uuid(UUID.randomUUID().toString());
			this.setIs_show("Y");
			this.setStatus("1");
			this.setCreate_user(opt.getSeq_id()+"");
			this.setCreate_time(new Date());
			this.setModify_user(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			this.save();
		}
		flashCatch(this);
		return this;
	}
	public void checkModelItem(){
		this.checkAdi_id("app下载ID标识");
		this.checkAdi_code("APP下载标识码");
		this.checkLanguage("语言");
		this.checkUser_type("APP下载用户类型");
		this.checkApp_type("APP下载app类型");
		this.checkQr_code_url("APP下载二维码图片");
		this.checkDescription("APP下载介绍");
	}
	/**
	 * 获取广告位列表
	 * @param user_type
	 * @param app_type
	 * @param language
	 * @param status
	 * @param page
	 * @return
	 */
	public Pair<List<Record>,PageKit<Record>> queryAppByPage(String user_type,String app_type, String language, String status, PageKit page){
		String sql = "select adi.seq_uuid," +
				"            adi.adi_id," +
				"            adi.adi_code," +
				"            adi.language," +
				"            adi.user_type," +
				"            adi.app_type," +
				"            adi.qr_code_url," +
				"            adi.description," +
				"            adi.orders," +
				"            adi.status," +
				"            adi.create_time," +
				"            userType.name userType_show," +
				"            appType.name appType_show," +
				"            status.name status_show," +
				"            is_show.name is_show_name" +
				"       from phjf_web_app_download_info adi" +
				"            left join sys_datalibrary userType on userType.parent_code = 'sys_deviceType' and userType.code = adi.user_type" +
				"            left join sys_datalibrary appType on appType.parent_code = 'sys_appType' and appType.code = adi.app_type" +
				"            left join sys_datalibrary status on status.parent_code = 'sys_status' and status.code = adi.status" +
				"            left join sys_datalibrary is_show on is_show.parent_code = 'sys_isShow' and is_show.code = adi.is_show" +
				"      where 1=1";
		List params = new ArrayList();
		if (F.validate.isNotEmpty(user_type)){
			sql += " and adi.user_type = ? ";
			params.add(user_type);
		}
		if (F.validate.isNotEmpty(app_type)){
			sql += " and adi.app_type = ? ";
			params.add(app_type);
		}
		if (F.validate.isNotEmpty(language)){
			sql += " and adi.language = ? ";
			params.add(language);
		}
		if (F.validate.isNotEmpty(status)){
			sql += " and adi.status = ? ";
			params.add(status);
		}
		sql += " order by adi.orders asc";
		return JFinalDbKit.paginate(Db.use("DBPublic"), page.getNowPage(), page.getRowsPerPage(), sql, params.toArray());
	}

	/**
	 * 通过ID获取广告位
	 * @param seq_uuid
	 * @return
	 */
	public WebAppDownloadInfo findById(String seq_uuid){
		String sql = "select * " +
				"       from phjf_web_app_download_info " +
				"      where seq_uuid = ? " +
				"      limit 1";
		WebAppDownloadInfo data = WebAppDownloadInfo.dao.use("DBPublic").findFirst(sql,seq_uuid);
		if(F.validate.isEmpty(data)){
			data = new WebAppDownloadInfo();
		}
		return data;
	}

	/**
	 *通过adi_code获取广告位
	 * @param adi_code
	 * @return
	 */
	public List<WebAppDownloadInfo> findByAppCode(String adi_code){
		String sql = "select * " +
				"       from phjf_web_app_download_info " +
				"      where adi_code = ? " +
				"        and status = 1 ";
		return WebAppDownloadInfo.dao.use("DBPublic").find(sql,adi_code);
	}

	/**
	 * 获取语言的中文名
	 * @return
	 */
	public String findLanguage_show(){
		SysDatalibrary library = SysDatalibrary.dao.queryDatalibrary("Phjf", "sys_language", this.getLanguage());
		return library.getName();
	}

	/**
	 * 通过code和语言获取广告位
	 * @param adi_code
	 * @param language
	 * @return
	 */
	public WebAppDownloadInfo findWebApp(String adi_code, String language){
		String sql = "select * " +
				"       from phjf_web_app_download_info " +
				"      where adi_code = ? " +
				"        and language = ?" +
				"        and status = 1" +
				"      limit 1";
		WebAppDownloadInfo data = WebAppDownloadInfo.dao.use("DBPublic").findFirst(sql,adi_code,language);
		if(F.validate.isEmpty(data)){
			data = new WebAppDownloadInfo();
		}
		return data;
	}
	/**
	 * 获取app列表
	 * @return
	 */
	public WebAppDownloadInfo queryAppList(String language, String user_type, String app_type){
		String sql = "select * " +
				"       from phjf_web_app_download_info " +
				"      where language = ? " +
				"        and user_type = ?" +
				"        and app_type = ?" +
				"        and is_show = 'Y'" +
				"        and status = '1' order by orders ";
		return WebAppDownloadInfo.dao.use("DBPublic").findFirst(sql,language, user_type, app_type);
	}
}
