package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.excep.MsgBusinessException;
import com.bankwel.framework.core.kit.JFinalDbKit;
import com.bankwel.framework.core.kit.PageKit;
import com.bankwel.phjf_admin.common.constants.admin.AdminConstants;
import com.bankwel.phjf_admin.common.model.core.base.BaseWebNewsInfo;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheWebNewsInfo;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import org.apache.commons.lang3.tuple.Pair;
import sun.misc.Cache;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebNewsInfo extends CacheWebNewsInfo<WebNewsInfo> {
	public static final WebNewsInfo dao = new WebNewsInfo().dao();

	/**
	 * 获取新闻文章列表
	 * @param np_name
	 * @param title
	 * @param publish_date
	 * @param language
	 * @param status
	 * @param page
	 * @return
	 */
	public Pair<List<Record>,PageKit<Record>> queryNewsArticleByPage(String np_name, String title, String publish_date, String language, String status, PageKit page){
		String sql = "select article.seq_uuid," +
				"            article.ni_id," +
				"            article.np_code," +
				"            article.ni_code," +
				"            article.title," +
				"            article.logo," +
				"            article.language," +
				"            article.publish_date," +
				"            article.tags," +
				"            article.source," +
				"            article.is_top," +
				"            article.is_recom," +
				"            article.status," +
				"            article.create_time," +
				"            status.name status_show," +
				"            is_show.name is_show_name," +
				"            is_top.name is_top_show," +
				"            is_recom.name is_recom_show," +
				"            plate.np_name np_name" +
				"       from phjf_web_news_info article" +
				"            left join phjf_web_news_plate plate on plate.np_code = article.np_code and plate.language = article.language" +
				"            left join sys_datalibrary status on status.parent_code = 'sys_articleStatus' and status.code = article.status" +
				"            left join sys_datalibrary is_show on is_show.parent_code = 'sys_isShow' and is_show.code = article.is_show" +
				"            left join sys_datalibrary is_top on is_top.parent_code = 'sys_yesNo' and is_top.code = article.is_top" +
				"            left join sys_datalibrary is_recom on is_recom.parent_code = 'sys_isRecom' and is_recom.code = article.is_recom" +
				"      where 1=1";
		List params = new ArrayList();
		if (F.validate.isNotEmpty(np_name)){
			sql += " and (article.np_code = ? or plate.np_name LIKE concat('%',?,'%'))";
			params.add(np_name);
			params.add(np_name);
		}
		if (F.validate.isNotEmpty(title)){
			sql += " and (article.title LIKE concat('%',?,'%') or article.ni_code = ?)";
			params.add(title);
			params.add(title);
		}
		if (F.validate.isNotEmpty(publish_date)){
			sql += " and article.publish_date = ?";
			params.add(publish_date);
		}
		if (F.validate.isNotEmpty(language)){
			sql += " and article.language = ? ";
			params.add(language);
		}
		if (F.validate.isNotEmpty(status)){
			sql += " and article.status = ? ";
			params.add(status);
		}
		sql += " order by article.create_time desc";
		return JFinalDbKit.paginate(Db.use("DBPublic"), page.getNowPage(), page.getRowsPerPage(), sql, params.toArray());
	}
	/**
	 * 通过ID获取新闻文章
	 * @param seq_uuid
	 * @return
	 */
	public WebNewsInfo findById(String seq_uuid){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where seq_uuid = ? " +
				"      limit 1";
		WebNewsInfo data = WebNewsInfo.dao.use("DBPublic").findFirst(sql,seq_uuid);
		if(F.validate.isEmpty(data)){
			data = new WebNewsInfo();
		}
		return data;
	}
	/**
	 * 通过code和语言获取新闻文章
	 * @param article_code
	 * @param language
	 * @return
	 */
	public WebNewsInfo findNewsArticle(String article_code,String language){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where ni_code = ? " +
				"        and language = ?" +
				"        and status !=3" +
				"      limit 1";
		WebNewsInfo data = WebNewsInfo.dao.use("DBPublic").findFirst(sql,article_code,language);
		if(F.validate.isEmpty(data)){
			data = new WebNewsInfo();
		}
		return data;
	}
	/**
	 * 获取新闻版块
	 * @return
	 */
	public WebNewsPlate findNewsPlate(){
		WebNewsPlate newsPlate = WebNewsPlate.dao.findNewsPlate(this.getNp_code(), AdminConstants.ZH_SIMP);
		if(F.validate.isEmpty(newsPlate)){
			newsPlate = new WebNewsPlate();
		}
		return newsPlate;
	}
	/**
	 * 获取语言的中文名
	 * @return
	 */
	public String findLanguage_show(){
		SysDatalibrary library = SysDatalibrary.dao.queryDatalibrary("Phjf", "sys_language", this.getLanguage());
		return library.getName();
	}
	/**
	 * 通过plate_code获取新闻文章
	 * @param plate_code
	 * @return
	 */
	public List<WebNewsInfo> findByPlateCode(String plate_code){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where np_code = ? " +
				"        and status !=3" +
				"      limit 1";
		return WebNewsInfo.dao.use("DBPublic").find(sql,plate_code);
	}
	/**
	 * 新增或修改新闻文章
	 * @param opt
	 * @return
	 */
	public WebNewsInfo saveOrUpdate(AuthOperator opt) throws MsgBusinessException{
		this.checkModelItem();
		if (F.validate.isNotEmpty(this.getNi_id()+"")&&!(this.getNi_id().equals(0))){
			this.setModify_user(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			if(F.validate.isEmpty(this.getIs_show())){
				this.setIs_show("Y");
			}
			this.update();
		} else {
			if (F.validate.isEmpty(this.getNi_code())){
				this.setNi_code(SysSeq.dao.generatorNiCode());
			}
			if(F.validate.isEmpty(this.getIs_recom())){
				this.setIs_recom("N");
			}
			if(F.validate.isEmpty(this.getIs_top())){
				this.setIs_top("N");
			}
			this.setSeq_uuid(UUID.randomUUID().toString());
			this.setIs_show("Y");
			this.setStatus("1");
			this.setCreate_user(opt.getSeq_id()+"");
			this.setCreate_time(new Date());
			this.setModify_user(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			this.save();
		}
		flashCatch(this);
		return this;
	}
	public void checkModelItem() {
		this.checkNp_code("新闻版块编码");
		this.checkNi_code("新闻内部编码");
		this.checkLanguage("语言");
		this.checkTitle("新闻标题");
		this.checkLogo("新闻logo地址");
		this.checkPublish_date("新闻发表日期");
		this.checkAuto_publish_date("新闻自动发布日期");
		this.checkTags("新闻标签");
		this.checkSource("新闻来源");
		this.checkContent("新闻内容");
		this.checkIs_top("新闻是否置顶");
		this.checkIs_recom("新闻是否推荐");
		this.checkIs_show("新闻是否显示");
		this.checkStatus("新闻状态");
	}
	/**
	 *通过文章标题和版块获取新闻文章
	 * @param plate_code
	 * @param title
	 * @return
	 */
	public WebNewsInfo findByArticleTitle(String plate_code, String title){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where np_code = ?" +
				"        and title = ? " +
				"        and status != 3 ";
		WebNewsInfo data = WebNewsInfo.dao.use("DBPublic").findFirst(sql,plate_code,title);
		if(F.validate.isEmpty(data)){
			data = new WebNewsInfo();
		}
		return data;
	}

	/**
	 * 修改前判断文章标题是否存在
	 * @param seq_uuid
	 * @param plate_code
	 * @param title
	 * @return
	 */
	public Boolean isHaveArticle(String seq_uuid, String plate_code, String title){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where seq_uuid != ? " +
				"        and np_code = ?" +
				"        and title = ?" +
				"        and status !=3" +
				"      limit 1";
		WebNewsInfo newsArticle = WebNewsInfo.dao.use("DBPublic").findFirst(sql,seq_uuid,plate_code,title);
		if(F.validate.isEmpty(newsArticle)){
			return false;
		}
		return true;
	}

	/**
	 *通过article_code获取新闻文章
	 * @param article_code
	 * @return
	 */
	public List<WebNewsInfo> queryByArticleCode(String article_code){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where ni_code = ? "+
				"        and status != 3 ";
		return WebNewsInfo.dao.use("DBPublic").find(sql,article_code);
	}

	public List<WebNewsInfo> queryIndexNews(String language,String np_code){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where language = ? " +
				"        and np_code = ? "+
				"        and status = '2' " +
				"        and is_recom = 'Y' order by publish_date desc ";
		return WebNewsInfo.dao.use("DBPublic").find(sql,language,np_code);
	}
	/**
	 * 通过code和语言获取新闻文章
	 * @param article_code
	 * @param language
	 * @return
	 */
	public WebNewsInfo findUnPublishArticle(String article_code,String language){
		String sql = "select * " +
				"       from phjf_web_news_info " +
				"      where ni_code = ? " +
				"        and language = ?" +
				"        and status = 3" +
				"      limit 1";
		WebNewsInfo data = WebNewsInfo.dao.use("DBPublic").findFirst(sql,article_code,language);
		if(F.validate.isEmpty(data)){
			data = new WebNewsInfo();
		}
		return data;
	}
}
