package com.bankwel.phjf_admin.common.model.core;

import com.bankwel.framework.core.F;
import com.bankwel.framework.core.excep.MsgBusinessException;
import com.bankwel.framework.core.kit.JFinalDbKit;
import com.bankwel.framework.core.kit.PageKit;
import com.bankwel.phjf_admin.common.model.core.base.BaseWebNewsPlate;
import com.bankwel.phjf_admin.component.c13webtag.bootstrap.DynamicSelectData;
import com.bankwel.phjf_admin.component.c13webtag.bootstrap.IDynamicSelectData;
import com.bankwel.phjf_baseModel.common.model.phjf.CacheWebNewsPlate;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import org.apache.commons.lang3.tuple.Pair;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WebNewsPlate extends CacheWebNewsPlate<WebNewsPlate> {
	public static final WebNewsPlate dao = new WebNewsPlate().dao();

	/**
	 * 获取新闻版块列表
	 * @param name
	 * @param language
	 * @param status
	 * @param page
	 * @return
	 */
	public Pair<List<Record>,PageKit<Record>> queryNewsPlateByPage(String name, String language, String status, PageKit page){
		String sql = "select plate.seq_uuid," +
				"            plate.np_id," +
				"            plate.np_code," +
				"            plate.language," +
				"            plate.np_name," +
				"            plate.order_num," +
				"            plate.type," +
				"            plate.location," +
				"            plate.nav_code," +
				"            plate.status," +
				"            plate.create_time," +
				"            type.name type_show," +
				"            location.name location_show , " +
				"            nav.nav_name, " +
				"            opt.operate_name create_opt_name ," +
				"            status.name status_show, " +
				"            is_show.name is_show_name" +
				"       from phjf_web_news_plate plate" +
				"            left join sys_datalibrary type on type.parent_code = 'web_newsModule' and type.code = plate.type" +
				"            left join sys_datalibrary location on location.parent_code = 'web_newsLocation' and location.code = plate.location" +
				"            left join phjf_web_nav nav on nav.nav_code = plate.nav_code and nav.language = plate.language " +
				"            left join auth_operator opt on opt.seq_id = plate.create_user" +
				"            left join sys_datalibrary status on status.parent_code = 'sys_status' and status.code = plate.status" +
				"            left join sys_datalibrary is_show on is_show.parent_code = 'sys_isShow' and is_show.code = plate.is_show" +
				"      where 1=1";
		List params = new ArrayList();
		if (F.validate.isNotEmpty(name)){
			sql += " and plate.np_name LIKE concat('%',?,'%') ";
			params.add(name);
		}
		if (F.validate.isNotEmpty(language)){
			sql += " and plate.language = ? ";
			params.add(language);
		}
		if (F.validate.isNotEmpty(status)){
			sql += " and plate.status = ? ";
			params.add(status);
		}
		sql += " order by plate.order_num ";
		return JFinalDbKit.paginate(Db.use("DBPublic"), page.getNowPage(), page.getRowsPerPage(), sql, params.toArray());
	}
	/**
	 *通过版块名称获取新闻版块
	 * @param name
	 * @return
	 */
	public WebNewsPlate findByPlateName(String name){
		String sql = "select * " +
				"       from phjf_web_news_plate " +
				"      where np_name = ? " +
				"        and status = 1" +
				"        and is_show = 'Y' ";
		WebNewsPlate data = WebNewsPlate.dao.use("DBPublic").findFirst(sql,name);
		if(F.validate.isEmpty(data)){
			data = new WebNewsPlate();
		}
		return data;
	}

	/**
	 * 新增或修改新闻版块
	 * @param opt
	 * @return
	 */
	public WebNewsPlate saveOrUpdate(AuthOperator opt) throws MsgBusinessException{
		this.checkModelItem();
		if (F.validate.isNotEmpty(this.getNp_id()+"")&&!(this.getNp_id().equals(0))){
			this.setModify_user(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			if(F.validate.isEmpty(this.getIs_show())){
				this.setIs_show("Y");
			}
			this.update();
		} else {
			if (F.validate.isEmpty(this.getNp_code())){
				this.setNp_code(SysSeq.dao.generatorWebNPCode());
			}
			this.setSeq_uuid(UUID.randomUUID().toString());
			this.setIs_show("Y");
			this.setStatus("1");
			this.setCreate_user(opt.getSeq_id()+"");
			this.setCreate_time(new Date());
			this.setModify_user(opt.getSeq_id()+"");
			this.setModify_time(new Date());
			this.save();
		}
		flashCatch(this);
		return this;
	}
	public void checkModelItem() {
		this.checkNp_code("新闻版块内部编码");
		this.checkLanguage("语言");
		this.checkNp_name("版块名称");
		this.checkType("新闻模块类型");
		this.checkLocation("版块展示位置");
		this.checkNav_code("新闻版块所属导航");
		this.checkOrder_num("新闻版块排序号");
	}
	/**
	 * 通过ID获取新闻版块
	 * @param seq_uuid
	 * @return
	 */
	public WebNewsPlate findById(String seq_uuid){
		String sql = "select * " +
				"       from phjf_web_news_plate " +
				"      where seq_uuid = ? " +
				"      limit 1";
		WebNewsPlate data = WebNewsPlate.dao.use("DBPublic").findFirst(sql,seq_uuid);
		if(F.validate.isEmpty(data)){
			data = new WebNewsPlate();
		}
		return data;
	}
	/**
	 * 获取语言的中文名
	 * @return
	 */
	public String findLanguage_show(){
		SysDatalibrary library = SysDatalibrary.dao.queryDatalibrary("Phjf", "sys_language", this.getLanguage());
		return library.getName();
	}
	/**
	 * 获取新闻版块
	 * @param plate_code
	 * @param language
	 * @return
	 */
	public WebNewsPlate findNewsPlate(String plate_code, String language) {
		String sql = "select * " +
				"       from phjf_web_news_plate " +
				"      where np_code = ? " +
				"        and language = ? " +
				"        and status = 1 " +
				"      limit 1 ";
		WebNewsPlate data = WebNewsPlate.dao.use("DBPublic").findFirst(sql, plate_code, language);
		if(F.validate.isEmpty(data)){
			data = new WebNewsPlate();
		}
		return data;
	}

	/**
	 * 修改前判断该新闻版块名称是否存在
	 * @param seq_uuid
	 * @param name
	 * @return
	 */
	public Boolean isHavePlate(String seq_uuid,String name){
		String sql = "select * " +
				"       from phjf_web_news_plate " +
				"      where seq_uuid !=? " +
				"        and np_name = ?" +
				"        and status = 1 ";
		WebNewsPlate data = WebNewsPlate.dao.use("DBPublic").findFirst(sql,seq_uuid,name);
		if(F.validate.isEmpty(data)){
			return false;
		}
		return true;
	}
	/**
	 *通过plate_code获取新闻版块
	 * @param plate_code
	 * @return
	 */
	public List<WebNewsPlate> findByPlateCode(String plate_code){
		String sql = "select * " +
				"       from phjf_web_news_plate " +
				"      where np_code = ? " +
				"        and status = 1 ";
		return WebNewsPlate.dao.use("DBPublic").find(sql,plate_code);
	}
}
