package com.bankwel.phjf_website.common.model.website.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppInfo<M extends BaseAppInfo<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setApp_id(java.lang.Integer app_id) {
		set("app_id", app_id);
	}

	public java.lang.Integer getApp_id() {
		return getInt("app_id");
	}

	public void setApp_code(java.lang.String app_code) {
		set("app_code", app_code);
	}

	public java.lang.String getApp_code() {
		return getStr("app_code");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public void setPackage_name(java.lang.String package_name) {
		set("package_name", package_name);
	}

	public java.lang.String getPackage_name() {
		return getStr("package_name");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setShare_count(java.lang.Integer share_count) {
		set("share_count", share_count);
	}

	public java.lang.Integer getShare_count() {
		return getInt("share_count");
	}

	public void setDownload_count(java.lang.Integer download_count) {
		set("download_count", download_count);
	}

	public java.lang.Integer getDownload_count() {
		return getInt("download_count");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

}
