package com.bankwel.phjf_website.common.model.website.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebAppDownloadInfo<M extends BaseWebAppDownloadInfo<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setAdi_id(java.lang.Integer adi_id) {
		set("adi_id", adi_id);
	}

	public java.lang.Integer getAdi_id() {
		return getInt("adi_id");
	}

	public void setAdi_code(java.lang.String adi_code) {
		set("adi_code", adi_code);
	}

	public java.lang.String getAdi_code() {
		return getStr("adi_code");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public void setUser_type(java.lang.String user_type) {
		set("user_type", user_type);
	}

	public java.lang.String getUser_type() {
		return getStr("user_type");
	}

	public void setApp_type(java.lang.String app_type) {
		set("app_type", app_type);
	}

	public java.lang.String getApp_type() {
		return getStr("app_type");
	}

	public void setQr_code_url(java.lang.String qr_code_url) {
		set("qr_code_url", qr_code_url);
	}

	public java.lang.String getQr_code_url() {
		return getStr("qr_code_url");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setOrders(java.lang.Integer orders) {
		set("orders", orders);
	}

	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_user(java.lang.String create_user) {
		set("create_user", create_user);
	}

	public java.lang.String getCreate_user() {
		return getStr("create_user");
	}

	public void setModify_user(java.lang.String modify_user) {
		set("modify_user", modify_user);
	}

	public java.lang.String getModify_user() {
		return getStr("modify_user");
	}

}
