package com.bankwel.phjf_website.common.model.website.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManagepointInfo<M extends BaseManagepointInfo<M>> extends Model<M> implements IBean {

	public void setSeq_uuid(java.lang.String seq_uuid) {
		set("seq_uuid", seq_uuid);
	}

	public java.lang.String getSeq_uuid() {
		return getStr("seq_uuid");
	}

	public void setMp_id(java.lang.Integer mp_id) {
		set("mp_id", mp_id);
	}

	public java.lang.Integer getMp_id() {
		return getInt("mp_id");
	}

	public void setMp_code(java.lang.String mp_code) {
		set("mp_code", mp_code);
	}

	public java.lang.String getMp_code() {
		return getStr("mp_code");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return getStr("contact");
	}

	public void setMobilephone(java.lang.String mobilephone) {
		set("mobilephone", mobilephone);
	}

	public java.lang.String getMobilephone() {
		return getStr("mobilephone");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setIs_withdraw(java.lang.String is_withdraw) {
		set("is_withdraw", is_withdraw);
	}

	public java.lang.String getIs_withdraw() {
		return getStr("is_withdraw");
	}

	public void setDay_total_amount(java.lang.Integer day_total_amount) {
		set("day_total_amount", day_total_amount);
	}

	public java.lang.Integer getDay_total_amount() {
		return getInt("day_total_amount");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return getStr("area");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setOpen_hours(java.lang.String open_hours) {
		set("open_hours", open_hours);
	}

	public java.lang.String getOpen_hours() {
		return getStr("open_hours");
	}

	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}

	public java.lang.String getLat() {
		return getStr("lat");
	}

	public void setLng(java.lang.String lng) {
		set("lng", lng);
	}

	public java.lang.String getLng() {
		return getStr("lng");
	}

	public void setGeohash(java.lang.String geohash) {
		set("geohash", geohash);
	}

	public java.lang.String getGeohash() {
		return getStr("geohash");
	}

	public void setEft_start_date(java.util.Date eft_start_date) {
		set("eft_start_date", eft_start_date);
	}

	public java.util.Date getEft_start_date() {
		return get("eft_start_date");
	}

	public void setEft_end_date(java.util.Date eft_end_date) {
		set("eft_end_date", eft_end_date);
	}

	public java.util.Date getEft_end_date() {
		return get("eft_end_date");
	}

	public void setEft_start_opt(java.lang.String eft_start_opt) {
		set("eft_start_opt", eft_start_opt);
	}

	public java.lang.String getEft_start_opt() {
		return getStr("eft_start_opt");
	}

	public void setEft_end_opt(java.lang.String eft_end_opt) {
		set("eft_end_opt", eft_end_opt);
	}

	public java.lang.String getEft_end_opt() {
		return getStr("eft_end_opt");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIs_show(java.lang.String is_show) {
		set("is_show", is_show);
	}

	public java.lang.String getIs_show() {
		return getStr("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreate_time(java.util.Date create_time) {
		set("create_time", create_time);
	}

	public java.util.Date getCreate_time() {
		return get("create_time");
	}

	public void setModify_time(java.util.Date modify_time) {
		set("modify_time", modify_time);
	}

	public java.util.Date getModify_time() {
		return get("modify_time");
	}

	public void setCreate_opt(java.lang.String create_opt) {
		set("create_opt", create_opt);
	}

	public java.lang.String getCreate_opt() {
		return getStr("create_opt");
	}

	public void setModify_opt(java.lang.String modify_opt) {
		set("modify_opt", modify_opt);
	}

	public java.lang.String getModify_opt() {
		return getStr("modify_opt");
	}

	public void setIs_confirm(java.lang.String is_confirm) {
		set("is_confirm", is_confirm);
	}

	public java.lang.String getIs_confirm() {
		return getStr("is_confirm");
	}

}
