package com.bankwel.phjf_admin.support.jfconfig;

import com.bankwel.framework.core.encrypt.AES;
import com.bankwel.framework.support.jfinal.AutoBindRoutes;
import com.bankwel.framework.support.jfinal.VelocityLayoutRenderFactory;
import com.bankwel.phjf_admin.common.model.core._PhjfMappingKit;
import com.bankwel.phjf_admin.support.FlowControlInterceptor;
import com.bankwel.phjf_admin.support.SessionInterceptor;
import com.jfinal.config.*;
import com.jfinal.core.Const;
import com.jfinal.ext.handler.ContextPathHandler;
import com.jfinal.kit.PropKit;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.jfinal.plugin.druid.DruidPlugin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by su_ln on 2016/2/5.
 */
public class Config extends JFinalConfig {

    private static final Logger log = LoggerFactory.getLogger(Config.class);

    public static AES aes = AES.getInstance("BfjDbKeyPass2017");

    public void configConstant(Constants me) {
        PropKit.use("config.properties");
        me.setDevMode(true);
//        me.setViewType(ViewType.JSP);
//        me.setViewType(ViewType.VELOCITY);
        me.setEncoding("UTF-8");
//        me.setViewExtension(".vm");
        me.setRenderFactory(new VelocityLayoutRenderFactory());
        me.setMaxPostSize(50* Const.DEFAULT_MAX_POST_SIZE);
        me.setError404View("/WEB-INF/velocity/error/error.jsp");
        me.setError500View("/WEB-INF/velocity/error/error.jsp");

    }

    public void configRoute(Routes me) {
        AutoBindRoutes bind = new AutoBindRoutes();
        bind.regist(me,"com.bankwel.phjf_admin");
    }

    public void configPlugin(Plugins me) {
        DruidPlugin DBPlugin = new DruidPlugin(PropKit.use("config.properties").get("public.db.url"), PropKit.use("config.properties").get("public.db.username"), aes.decode(PropKit.use("config.properties").get("public.db.password")));
        DBPlugin.setInitialSize(1) //配置初始化大小
                .setMinIdle(1) //配置最小数量
                .setMaxActive(10) //配置最大数量
                .setTimeBetweenEvictionRunsMillis(60000) //<!-- 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
                .setMinEvictableIdleTimeMillis(300000) //配置一个连接在池中最小生存的时间，单位是毫秒
                .setValidationQuery("select 1")
//                .setMaxPoolPreparedStatementPerConnectionSize(200)
                .setTestWhileIdle(true).setTestOnBorrow(true).setTestOnReturn(true);
//                .setFilters("stat");
        me.add(DBPlugin);

        ActiveRecordPlugin arpPublic = new ActiveRecordPlugin("DBPublic", DBPlugin);
        _PhjfMappingKit.mapping(arpPublic);
        arpPublic.setShowSql(true);

        me.add(arpPublic);

//        me.add(new SpringPlugin());

    }

    public void configInterceptor(Interceptors me) {
        me.add(new SessionInterceptor());
        me.add(new FlowControlInterceptor());
    }

    public void configHandler(Handlers me) {
        me.add(new ContextPathHandler("path"));
//        DruidStatViewHandler dvh =  new DruidStatViewHandler("/druid");
//        me.add(dvh);
    }

    public void configEngine(com.jfinal.template.Engine var1){
    }

}
