package com.bankwel.phjf_admin.common.model;

import com.bankwel.framework.core.encrypt.AES;
import com.bankwel.framework.support.jfinal.PublicMappingKitGenerator;
import com.bankwel.framework.support.jfinal.PublicMetaBuilder;
import com.jfinal.kit.PathKit;
import com.jfinal.kit.PropKit;
import com.jfinal.plugin.activerecord.generator.Generator;
import com.jfinal.plugin.druid.DruidPlugin;

/**
 * Generated by su_ln on 2016/2/19.
 */
public class PhjfAdminModelCreater {

    public static AES aes = AES.getInstance("BfjDbKeyPass2017");

    /**
     * Main方法
     * @param args
     */
    public static void main(String[] args){
        createFrontier();
    }

    public static void createFrontier(){
        PropKit.use("config.properties");
//        System.out.println(PropKit.get("public.db.url"));
        DruidPlugin DBPlugin = new DruidPlugin(PropKit.get("public.db.url"), PropKit.get("public.db.username"), aes.decode(PropKit.get("public.db.password")));
//        DruidPlugin DBPlugin = new DruidPlugin(PropKit.get("public.db.url"), "root", "admin");
        DBPlugin.start();

        String basePack = "com.bankwel.phjf_admin.common.model.core.base";
        String modelPack = "com.bankwel.phjf_admin.common.model.core";
        String baseOutPackDir  = PathKit.getRootClassPath()+"/../../src/main/java/com/bankwel/phjf_admin/common/model/core/base";
        String modelOutPackDir = PathKit.getRootClassPath()+"/../../src/main/java/com/bankwel/phjf_admin/common/model/core/";
        Generator g = new Generator(DBPlugin.getDataSource(),basePack,baseOutPackDir,modelPack,modelOutPackDir);

        PublicMetaBuilder mb = new PublicMetaBuilder(DBPlugin.getDataSource());
        mb.addIncludedTable("auth_resource");
        mb.addIncludedTable("auth_resource_service");
        mb.addIncludedTable("auth_service");
        mb.addIncludedTable("auth_operator");
        mb.addIncludedTable("auth_role");
        mb.addIncludedTable("auth_operator_auth");
        mb.addIncludedTable("auth_role_resource");
        mb.addIncludedTable("auth_branch");
        mb.addIncludedTable("auth_branch_apply");
        mb.addIncludedTable("sys_apply_center");
        mb.addIncludedTable("sys_datalibrary");

        mb.addIncludedTable("phjf_managepoint_info");
        mb.addIncludedTable("phjf_managepoint_bank");
        mb.addIncludedTable("phjf_managepoint_optinfo");
        mb.addIncludedTable("phjf_bank_type");
        mb.addIncludedTable("phjf_bank_info");
        mb.addIncludedTable("phjf_bank_optinfo");
        mb.addIncludedTable("phjf_bank_deposit_info");
        mb.addIncludedTable("phjf_news_plate");
        mb.addIncludedTable("phjf_news_article");
        mb.addIncludedTable("phjf_banner_info");
        mb.addIncludedTable("phjf_user_info");
        mb.addIncludedTable("phjf_user_appauth");
        mb.addIncludedTable("phjf_user_bankcard_appointment");
        mb.addIncludedTable("phjf_user_withdraw_appointment");
        mb.addIncludedTable("phjf_user_loan_apply");
        mb.addIncludedTable("phjf_user_feedback");
        mb.addIncludedTable("phjf_user_bankcard");
        mb.addIncludedTable("phjf_user_loan_bank_process");
        mb.addIncludedTable("phjf_financial_product");
        mb.addIncludedTable("phjf_loan_info");
        mb.addIncludedTable("sys_seq");//
        mb.addIncludedTable("sys_provinces");//
        mb.addIncludedTable("sys_cities");//
        mb.addIncludedTable("sys_areas");//
        mb.addIncludedTable("phjf_app_info");//
        mb.addIncludedTable("phjf_app_version_info");//
        mb.addIncludedTable("phjf_bank_atm");//
        mb.addIncludedTable("phjf_bank_bankcard_tradelog");
        mb.addIncludedTable("phjf_financial_fund");
        mb.addIncludedTable("phjf_sms_log");
        mb.addIncludedTable("sys_param");
        mb.addIncludedTable("phjf_web_nav");//
        mb.addIncludedTable("phjf_web_banner");//
        mb.addIncludedTable("phjf_web_news_plate");//
        mb.addIncludedTable("phjf_web_news_info");//
        mb.addIncludedTable("phjf_web_app_download_info");//
        mb.addIncludedTable("phjf_web_partner");//
        mb.addIncludedTable("phjf_web_links");//
        mb.addIncludedTable("phjf_web_about_us");//
        mb.addIncludedTable("sys_sensitiveWords_library");//
        mb.addIncludedTable("phjf_bank_business_setting");//
        mb.addIncludedTable("phjf_bank_business_config");//
        mb.addIncludedTable("phjf_appointment_time");//
        mb.addIncludedTable("phjf_policy_article");
        mb.addIncludedTable("phjf_policy_article_plate");
        mb.addIncludedTable("phjf_policy_article_search");
        mb.addIncludedTable("phjf_policy_plate");
        mb.addIncludedTable("phjf_policy_plate_city");
        mb.addIncludedTable("phjf_search_terms");
        mb.addIncludedTable("phjf_sms_code");
        mb.addIncludedTable("phjf_user_login_log");

//        mb.addIncludedTable("");//
//        mb.addIncludedTable("");//
//        mb.addIncludedTable("");//
        g.setMetaBuilder(mb);
        g.setMappingKitGenerator(new PublicMappingKitGenerator(modelPack, modelOutPackDir,"_PhjfMappingKit"));
        g.setGenerateDaoInModel(true);
        g.setGenerateDaoInModel(true);
        g.setRemovedTableNamePrefixes("phjf_");
        g.generate();
    }

}
